# 基础镜像：jdk
FROM openjdk:8-jdk

# 设置容器时间
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

#用于在 Linux 系统中设置时区的命令。具体来说，它会将系统的本地时间设置为上海时间（Asia/Shanghai 时区）。以下是这条命令的详细解释：
#ln: 这是一个用于创建链接的命令。
#-s: 这是 ln 命令的一个选项，表示创建一个符号链接（软链接），而不是硬链接。
#-f: 这是 ln 命令的另一个选项，表示如果目标文件已经存在，强制删除它然后创建新的链接。
#/usr/share/zoneinfo/Asia/Shanghai: 这是指向上海时区信息文件的路径。
#/etc/localtime: 这是系统本地时间设置的文件位置。
#这条命令的作用是将 /usr/share/zoneinfo/Asia/Shanghai 文件（代表上海时区）链接到 /etc/localtime，这样系统就会使用上海时区作为本地时间。

#用于设置系统的时区信息，具体是将系统时区设置为上海时区（Asia/Shanghai）。以下是这条命令的详细解释：
#echo 'Asia/Shanghai': 这是一个将字符串 Asia/Shanghai 输出到标准输出的命令。
#>/etc/timezone: 这是一个重定向操作符，将 echo 命令的输出写入 /etc/timezone 文件中，覆盖文件中已有的内容。
#这条命令的作用是将 Asia/Shanghai 写入到 /etc/timezone 文件中。/etc/timezone 文件通常用于存储系统的时区设置，很多 Linux 发行版和工具会读取这个文件来确定系统的时区。
#这条命令和前面的 ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 命令通常会一起使用，以确保系统的时区设置正确。前者设置了时区信息，后者实际更改了时区文件链接。

#JVM（Java）默认时区来源顺序（Linux 上）

#JVM 启动时，如果没有显式设置 -Duser.timezone，会按照以下顺序尝试确定默认时区：
#	1.	环境变量 TZ（某些 JVM 实现会参考，但并不稳定）
#	2.	/etc/timezone 文件（某些 Linux 发行版存在此文件）
#	3.	/etc/localtime 文件链接的目标文件
#	4.	默认 UTC（以上都失败）

#这两步：
#	1.	设置了系统当前时区实际链接为 Asia/Shanghai；
#	2.	设置了 /etc/timezone 明确指定 Asia/Shanghai；
#
#因此，在 JVM 启动时，它读取了这些配置文件，正确识别出了系统时区，从而自动设置 user.timezone=Asia/Shanghai，即便你没有手动指定




# 上传jar
ARG JAR_FILE
ADD ${JAR_FILE} /usr/local/myapp/myapp.jar

#添加宋体：用于宋体业务
ARG CFG
ADD ${CFG}/fonts /usr/share/fonts/chinese

# 设置容器默认工作目录
WORKDIR /usr/local/myapp

# 声明变量：使用宿主机变量
ENV JAVA_OPTS=$JAVA_OPTS

# 设置容器启动执行的命令
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /usr/local/myapp.jar"]