# 基础镜像：jdk
FROM openjdk:8-jdk

# 设置容器时间
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

# 上传jar
ARG JAR_FILE
ADD ${JAR_FILE} /usr/local/myapp/myapp.jar

#添加宋体：基础镜像可能没有
ARG CFG
ADD ./config/fonts /usr/share/fonts/chinese

# 设置容器默认工作目录
WORKDIR /usr/local/myapp

# 设置容器启动执行的命令
ENTRYPOINT ["java","-jar","/usr/local/myapp/myapp.jar"]