FROM openjdk:11

# 设置Tomcat版本
ENV TOMCAT_VERSION 9.0.62

# 下载并解压Tomcat到/usr/local目录下
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -O /tmp/tomcat.tar.gz \
    && tar -xf /tmp/tomcat.tar.gz -C /usr/local \
    && mv /usr/local/apache-tomcat-${TOMCAT_VERSION} /usr/local/tomcat \
    && rm /tmp/tomcat.tar.gz

# 设置环境变量
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

# 删除不必要的应用和示例
RUN rm -rf $CATALINA_HOME/webapps/

# 启动Tomcat服务器
CMD ["catalina.sh", "run"]