version: '3.3'

#服务定义
services:
  sysapi:
    image: "reg.int.it2000.com.cn/com.gzzn.gxts/sys-api:latest"
    working_dir: /usr/local/myapp
    volumes:
     - /etc/localtime:/etc/localtime
#    这个挂载了宿主机的 /etc/localtime，但并没有 /etc/timezone 文件，也没有 TZ 环境变量。
#    如果 JVM 在你的容器基础镜像里没检测到 /etc/timezone 或失败识别 /etc/localtime 的符号链接，就会退回到 UTC。不同的 JDK 实现（OpenJDK、Zulu、Alpine JDK 等）表现也不完全一样。

    entrypoint: ["java","-XX:PermSize=64m","-XX:MaxPermSize=128m", "-Xms256m", "-Xmx1024m","-Dspring.profiles.active=dev","-Duser.timezone=Asia/Shanghai","-jar","/usr/local/myapp/myapp.jar"]
    networks: 
     - gxtsnw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure		

  gxtsweb:
    image: "reg.int.it2000.com.cn/com.gzzn.gxts/gxtsweb:latest"
    networks:
     - gxtsnw
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  gateway:
    image: "reg.int.it2000.com.cn/com.gzzn.gxts/gateway-api:latest"
    working_dir: /usr/local/myapp
    volumes:
      - /etc/localtime:/etc/localtime
    entrypoint: ["java","-XX:PermSize=64m","-XX:MaxPermSize=128m", "-Xms256m", "-Xmx1024m","-Dspring.profiles.active=test","-Duser.timezone=Asia/Shanghai","-jar","/usr/local/myapp/myapp.jar"]
    networks:
     - gxtsnw
    ports:
     - "81:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  taskapi:
    image: "reg.int.it2000.com.cn/com.gzzn.gxts/flowable-task:test-1"
    working_dir: /usr/local/myapp
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
     JAVA_OPTS: "-XX:PermSize=64m -XX:MaxPermSize=128m -Xms256m -Xmx1024m -Dspring.profiles.active=uat -Dapp.dataCenter.appHost=http://10.201.38.217:18110 -Duser.timezone=Asia/Shanghai"
     SPRING_PROFILES_ACTIVE: "uat"
     APP_DATACENTER_APPHOST: "http://10.201.38.217:18110"
    networks:
     - gxtsnw
    ports:
     - "84:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  msg-cim:
    image: "reg.int.it2000.com.cn/com.aifa.mins/msg-cim/1.0.0-snapshot:latest"
    networks:
     - gxtsnw
    ports:
     - "90:8080"
     - "34567:34567"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

#网络定义
networks:
  gxtsnw:
    ipam:
      config:
        - subnet: 132.39.0.0/16

#网络定义 ：外置（不推荐）
#networks:
#  gxtsnw:
#    external: true

